"""json data updated

Revision ID: bcd06c937d0f
Revises: e1344a9aef10
Create Date: 2024-01-11 01:08:53.686945

"""
from typing import Sequence, Union
import sqlalchemy_utils

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bcd06c937d0f"
down_revision: Union[str, None] = "e1344a9aef10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "completed_content_blocks",
        sa.Column("url", sqlalchemy_utils.types.url.URLType(), nullable=True),
    )
    op.add_column(
        "completed_content_blocks",
        sa.Column("content", sa.Text(), nullable=True),
    )
    op.drop_column("completed_content_blocks", "type")
    op.add_column(
        "content_blocks", sa.Column("section_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "content_blocks_course_id_fkey", "content_blocks", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "content_blocks", "sections", ["section_id"], ["id"]
    )
    op.drop_column("content_blocks", "course_id")
    op.add_column(
        "courses", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("courses_course_id_fkey", "courses", type_="foreignkey")
    op.create_foreign_key(None, "courses", "users", ["user_id"], ["id"])
    op.drop_column("courses", "course_id")
    op.add_column(
        "sections", sa.Column("course_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("sections_user_id_fkey", "sections", type_="foreignkey")
    op.create_foreign_key(None, "sections", "courses", ["course_id"], ["id"])
    op.drop_column("sections", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sections",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "sections", type_="foreignkey")
    op.create_foreign_key(
        "sections_user_id_fkey", "sections", "courses", ["user_id"], ["id"]
    )
    op.drop_column("sections", "course_id")
    op.add_column(
        "courses",
        sa.Column(
            "course_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "courses", type_="foreignkey")
    op.create_foreign_key(
        "courses_course_id_fkey", "courses", "users", ["course_id"], ["id"]
    )
    op.drop_column("courses", "user_id")
    op.add_column(
        "content_blocks",
        sa.Column(
            "course_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "content_blocks", type_="foreignkey")
    op.create_foreign_key(
        "content_blocks_course_id_fkey",
        "content_blocks",
        "sections",
        ["course_id"],
        ["id"],
    )
    op.drop_column("content_blocks", "section_id")
    op.add_column(
        "completed_content_blocks",
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("completed_content_blocks", "content")
    op.drop_column("completed_content_blocks", "url")
    # ### end Alembic commands ###
